In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
## this script will build a neural network clissifer to slove XOR problem.
## this neural network has a input layer with 2 cells and 1 hidden layer with 3 cells, and a output layer with 1 cell

data  = np.array([[0,0],[0,1],[1,0],[1,1]])
label = np.array([[0],[1],[1],[0]])

In [6]:
%%html
<img src="https://images2015.cnblogs.com/blog/1035701/201704/1035701-20170414195906923-1457391618.png", width=600>

In [21]:
## initiate weight and offset

weight_L1 = np.random.randn(3,2)
weight_L2 = np.random.randn(3,1)

offset =np.ones(3)/4

print('weight_L1 is:', weight_L1)
print('weight_L2 is:', weight_L2)
print('offset is:', offset)
learning_rate = 0.05

weight_L1 is: [[ 1.08992839  0.45456791]
 [-1.00621354  0.65371067]
 [ 1.12979661  2.86427326]]
weight_L2 is: [[1.60787425]
 [0.47556858]
 [2.51928563]]
offset is: [0.25 0.25 0.25]


In [8]:
## intiate activation function
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))
    
    
def der_sigmoid(x):
    return (x * (1 - x))


def Relu(x):
    if x < 0:
        return 0
    else:
        return x
    
def der_Relu(x):
    if x < 0:
        return 0
    else:
        return 1


In [11]:
## forward prop

forwards = sigmoid(sigmoid(np.dot(data, weight_L1.T) + offset).dot(weight_L2))
out_hidden = np.dot(data, weight_L1.T) + offset
# print(forwards)
## lost 
lost =  ((label- forwards) ** 2)/2
lost = lost.sum()

In [12]:
deltaE_deltaOut = label - forwards
deltaOut_deltaNet = forwards * (1 - forwards)
deltaNet_delta = forwards

print(deltaE_deltaOut)
print(deltaOut_deltaNet)
print(deltaNet_delta)
print(out_hidden)
np.dot(deltaE_deltaOut, deltaOut_deltaNet.T).dot(deltaNet_delta)

[[-0.41693907]
 [ 0.49987015]
 [ 0.62660361]
 [-0.45293881]]
[[0.24310088]
 [0.24999998]
 [0.23397153]
 [0.24778524]]
[[0.41693907]
 [0.50012985]
 [0.37339639]
 [0.45293881]]
[[ 0.25        0.25        0.25      ]
 [-0.12881999 -1.17177402  1.80035623]
 [ 1.11821271 -0.31028182 -0.12158142]
 [ 0.73939273 -1.73205584  1.4287748 ]]


array([[-0.17761037],
       [ 0.21293788],
       [ 0.26692461],
       [-0.19294577]])

In [20]:
## update weight 
np.dot(deltaE_deltaOut,deltaOut_deltaNet.T,).dot(out_hidden).sum(axis = 0)



weight_L2

array([[-0.88080018],
       [-0.27125624],
       [ 0.55553274]])

In [22]:
np.dot(deltaE_deltaOut,deltaOut_deltaNet.T,).dot(data)

array([[-0.20086322, -0.20754611],
       [ 0.24081583,  0.24882798],
       [ 0.30187053,  0.31191402],
       [-0.21820634, -0.22546625]])

In [9]:
def xor_model(lr)
    global weight_L1, weight_L2, lost
    out = sigmoid(sigmoid(np.dot(data, weight_L1.T) + offset).dot(weight_L2))
    
    lost =  ((label- forwards) ** 2)/2
    
## back prop layer2

    deltaE_deltaOut = label - forwards
    deltaOut_deltaNet = forwards * (1 - forwards)
    deltaNet_delta = out_hidden
    W2_delta = np.dot(deltaE_deltaOut,deltaOut_deltaNet.T,).dot(out_hidden).sum(axis = 0)
    
    weight_L2 += lr * W2_delta
    
    ## layer 1 weight update
    
    
    

SyntaxError: invalid syntax (<ipython-input-9-19110a46eebd>, line 1)

In [ ]:
## reference https://www.cnblogs.com/wlzy/p/7751297.html

In [ ]:
data

In [ ]:
weight_L1

In [ ]:
sigmoid(np.dot(data, weight_L1.T) + offset).dot(weight_L2)

In [ ]:
weight_L2